# Site settings
title:          Daniel
description:    "Personal site test"
baseurl:        "/tl"
url:            "https://daeshu.github.io/tl"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Daniel Escobar
  url:          https://escobar.eu.org
  email:        daniel@escobar.eu.org

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
